CREATE TABLE IF NOT EXISTS movies (
                                      id SERIAL PRIMARY KEY,
                                      title VARCHAR(255),
    year VARCHAR(4),
    rated VARCHAR(50),
    released DATE,
    runtime VARCHAR(10),
    genre VARCHAR(255),
    director VARCHAR(255),
    writer VARCHAR(255),
    actors VARCHAR(255),
    plot TEXT,
    language VARCHAR(50),
    country VARCHAR(50),
    awards VARCHAR(255),
    poster VARCHAR(255),
    ratings JSONB,
    metascore VARCHAR(5),
    imdb_rating VARCHAR(5),
    imdb_votes VARCHAR(20),
    imdb_id VARCHAR(20),
    type VARCHAR(20),
    dvd DATE,
    box_office VARCHAR(50),
    production VARCHAR(255),
    website VARCHAR(255),
    response VARCHAR(5),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );